# Nom de l'application mobile
name: avapp
# Description de l'application mobile
description: "Application de gestion des stimuli visuels et auditifs pour les personnes présentant un trouble du spectre de l'autisme"

# Option pour la publication sur pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Gestion de version pour les appareils Android : https://developer.android.com/studio/publish/versioning
version: 0.0.0+1

environment:
  sdk: ^3.6.0

# Gestion des dépendances
# MAJ des dépendances `flutter pub upgrade --major-versions`. 
# Pour voir les versions disponibles, exécutez `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Ajout des logo CupertinoIcons pour IOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

# Information sur Dart : https://dart.dev/tools/pub/pubspec

# Paquet Flutter 
flutter:

  # Utilisation des icones provenant de Material Design
  uses-material-design: true

  # Ajout de fichiers ou d'images dans l'application (assets)
  # Résolution et variants : https://flutter.dev/to/resolution-aware-images
  # Assets provenant de package : https://flutter.dev/to/assets-and-images
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # Gestion des polices dans l'application : https://flutter.dev/to/font-from-packages
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 